<a href="https://colab.research.google.com/github/ignacio727/03MAIR-Algoritmos-de-Optimizacion-2020/blob/main/03MAIR-Algoritmos%20de%20optimizacion/SEMINARIO/Ignacio_de_Jaime_Seminario_Algoritmos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Algoritmos de optimización - Seminario<br>
Nombre y Apellidos: Ignacio de Jaime Hernández  <br>

Url Colab: https://colab.research.google.com/drive/18YRvIjXVhA_o3yCHMc9or_NJyrK71Vss?usp=sharing

Url: https://github.com/ignacio727/03MAIR-Algoritmos-de-Optimizacion-2020/tree/main/03MAIR-Algoritmos%20de%20optimizacion/SEMINARIO<br>
Problema:
> 1. Organizar sesiones de doblaje <br>
><strike>2. Organizar los horarios de partidos de La Liga</strike> <br>
><strike>3. Combinar cifras y operaciones</strike>

Descripción del problema:
Se precisa coordinar el doblaje de una película. Los actores del doblaje deben coincidir en las
tomas en las que sus personajes aparecen juntos en las diferentes tomas. Los actores de
doblaje cobran todos la misma cantidad por cada día que deben desplazarse hasta el estudio
de grabación independientemente del número de tomas que se graben. No es posible grabar
más de 6 tomas por día. El objetivo es planificar las sesiones por día de manera que el gasto
por los servicios de los actores de doblaje sea el menor posible. Los datos son:

Número de actores: 10

Número de tomas : 30

Actores/Tomas : https://bit.ly/36D8IuK

....

(*) La respuesta es obligatoria





                                        

(*)¿Cuantas posibilidades hay sin tener en cuenta las restricciones?<br>

A la hora de afrontar como ordenar todas las posibilidades, se puede ver que la selección de tomas para cada día se puede representar como un árbol, donde cada nivel del árbol serían las tomas seleccionadas para un día. El primer nivel serían las tomas del primer día, el segundo nivel las del segundo día y así sucesivamente.

Con esto en mente y si uno realiza los casos para 1, 2 y 3 tomas, se puede ir viendo un patrón que se va repitiendo. Llamando $P_{n}$ a las posibilidades de seleccionar $n$ tomas sin ninguna restricción, entonces:

$$P_{1}=1$$
$$P_{2}=3$$
$$P_{3}=13$$

El caso de $P_{1}$ es trivial y es partir de los siguientes casos donde se va a poder ver como se construyen. Para el caso de $P_{2}$ las posiblididades son, si designamos a las distintas tomas como letras:

<figure>
<center>
<img src='https://drive.google.com/uc?export=view&id=13yMQyOdSRMtQMsPX4dGFzkxi8JClKZU8' width="300" height="300"/>
<figcaption>Árbol de decisión para N=2</figcaption></center>
</figure>

Es decir, el caso de seleccionar la toma $A$ el primer día y la $B$ el segundo día, seleccionar primero la $B$ y luego la $A$, y seleccionar ambas tomas el primer día. Para 2 tomas aún sigue siendo algo difícil de ver, es ya para $P_{3}$ donde se puede observar más claro el patrón para cualquier número de tomas.

<figure>
<center>
<img src='https://drive.google.com/uc?export=view&id=1DMFSPoGOCqgc5ztiZgvwRAfNlL5RBejy' width="720" height="300"/>
<figcaption>Árbol de decisión para N=3</figcaption></center>
</figure>

Se puede comprobar como efectivamente hay 13 nodos finales. La clave aquí está en fijarse que los 3 sub-árboles de la izquierda cuyas raíces son A, B y C son exactamente iguales al arbol de decisión del caso de 2 tomas, lo cual tiene lógica porque una vez seleccionada 1 toma, quedarían 2 tomas restantes para seleccionar, lo cual es exáctamente el caso $P_{2}$.

Igualmente los 3 sub-árboles más a la derecha cuyas raíces son AB, AC y BC son los casos $P_{1}$, ya que una vez seleccionadas 2 tomas solamente quedaría 1 restante. Y por último, el nodo más a la derecha sería algo así como el caso $P_{0}$, el cual valdría 1.

Por tanto, lo único que quedaría por averiguar sería cuantos casos $P_{0}$, $P_{1}$ y $P_{2}$ hay dentro del arbol de decisión, lo cual es preguntarse cuantas formas hay de combinar sin repetición las 3 tomas, para grupos de 3 elementos (sub-árbol $P_{0}$), grupos de 2 elementos (sub-árboles $P_{1}$) y grupos de 1 elemento (sub-árboles $P_{2}$). 

La respuesta a esta pregunta la da la rama de las matemáticas de combinatoria. Por tanto $P_{3}$ se puede calcular como:

$$P_{3}=\begin{pmatrix}3\\
3
\end{pmatrix}P_{0}+\begin{pmatrix}3\\
2
\end{pmatrix}P_{1}+\begin{pmatrix}3\\
1
\end{pmatrix}P_{2}$$

Recordar que:

$$\begin{pmatrix}n\\
p
\end{pmatrix}=\frac{n!}{p!\left(n-p\right)!}$$

Si se generaliza quedaría lo siguiente:

$$P_{n}=\begin{pmatrix}n\\
n
\end{pmatrix}P_{0}+\begin{pmatrix}n\\
n-1
\end{pmatrix}P_{1}+\begin{pmatrix}n\\
n-2
\end{pmatrix}P_{2}+\cdots+\begin{pmatrix}n\\
1
\end{pmatrix}P_{n-1}$$

Lo cual puesto en forma de sumatorio es:

$$P_{n}=\sum_{i=0}^{n-1}\begin{pmatrix}n\\
n-i
\end{pmatrix}P_{i}$$

Siendo $P_{0}=1$.

De esta forma se puede calcular de forma iteraritiva todas las posibilidades.


In [132]:
from math import factorial

def posibilidades_sin_restriccion(N):
  P = [1] # P[0]
  for n in range(1, N+1): # Calculo de todas las P_n intermedias
    sum = 0
    for i in range(n): # Sumatorio para calcular cada P_n
      sum += (factorial(n) // (factorial(n-i) * factorial(i))) * P[i] 

    P.append(sum)
  return P

print('P_3 =', posibilidades_sin_restriccion(3)[-1])
print('Las posibilidades sin restricción para 30 tomas son %0.4e' 
      %posibilidades_sin_restriccion(30)[-1])

P_3 = 13
Las posibilidades sin restricción para 30 tomas son 1.1404e+37


¿Cuantas posibilidades hay teniendo en cuenta todas las restricciones?

Si se tienen en cuenta las restricciones entonces las posibilidades disminuyen. Para calcular este nuevo caso se va a usar el mismo método que cuando no había restricciones. Es decir, se va a ver la cantidad de posibilidades para un número de tomas reducido para una cierta restricción y ver como construirlos. Llamando $_{r}P_{n}$ al número de posibilidades para $n$ tomas y la restricción de $r$ tomas como máximo para cada día, entonces:

$$_{2}P_{1}=1$$
$$_{2}P_{2}=3$$
$$_{2}P_{3}=12$$

Para empezar, fijarse que en aquellos casos donde $r\geq n$ el número de posibilidades va a ser el mismo que para el caso sin restricciones, lo cual es lógico, ya que si la restricción es igual o mayor al número de tomas, entonces es equivalente a no tener restricciones. Es en los casos donde $r<n$ donde está lo interesante. Si se sigue una estructura análoga al caso sin restricciones, entonces no es díficil darse cuenta que aquellas combinaciones donde los grupos son de más elementos que $r$ no están permitidas. Por tanto, el caso de $_{2}P_{3}$, se podría construir como:

$$_{2}P_{3}=\begin{pmatrix}3\\
2
\end{pmatrix}{}_{2}P_{1}+\begin{pmatrix}3\\
1
\end{pmatrix}{}_{2}P_{2}$$

Fijarse que el caso $\begin{pmatrix}3\\
3
\end{pmatrix}{}_{2}P_{0}$ no estaría permitido por la restricción. Esta formulación se puede generalizar como:

$$_{r}P_{n}=\begin{pmatrix}n\\
r
\end{pmatrix}{}_{r}P_{n-r}+\begin{pmatrix}n\\
r-1
\end{pmatrix}{}_{r}P_{n-r+1}+\cdots+\begin{pmatrix}n\\
1
\end{pmatrix}{}_{r}P_{n-1}$$

Lo cual puesto en forma de sumatorio queda:

$$_{r}P_{n}=\sum_{i=n-r}^{n-1}\begin{pmatrix}n\\
n-i
\end{pmatrix}{}_{r}P_{i};\;\mathrm{si}\,\,r>n\,\,\mathrm{entonces\,\,}r=n$$

Hay que tener cuidado con esta formula ya que en el cálculo de los $_{r}P_{n}$ donde $r>n$ aparecerían $i$ negativos. Como todos esos casos son equivalentes al sin restricción, es decir, $r=n$, habría que poner la condición de que si $r>n$ entonces $r=n$ para ese caso. Destacar a parte del caso $r=n$, equivalente a no tener restricciones, el caso $r=1$, este sería el más restrictivo e equivalente al problema de ordenar $n$ elementos, es decir, $n!$.  

Puesto en Python quedaría:

In [133]:
def posibilidades(R, N):
  P = [1] # r_P[0]
  for n in range(1, N+1): # Calculo de todas las r_P_n intermedias
    sum = 0
    if R>n: # Condición para evitar i negativas
      r = n
    else:
      r = R
    for i in range(n-r, n): # Sumatorio para calcular cada r_P_n
      sum += (factorial(n) // (factorial(n-i) * factorial(i))) * P[i] 

    P.append(sum)
  return P

print('2_P_3 =', posibilidades(2, 4)[-1])
print('Las posibilidades sin restricción para 30 tomas son %0.0i = %0.6e' 
      %(posibilidades(30, 30)[-1], posibilidades(30, 30)[-1]))
print('Las posibilidades con restricción para 30 tomas son %0.0i = %0.6e' 
      %(posibilidades(6, 30)[-1], posibilidades(6, 30)[-1]))

2_P_3 = 66
Las posibilidades sin restricción para 30 tomas son 11403568794011880483742464196184901963 = 1.140357e+37
Las posibilidades con restricción para 30 tomas son 11400192964820635839099878586991366320 = 1.140019e+37


Fijarse que aunque con la restricción la cantidad de posibilidades se reduce, para lo datos del problema sigue siendo del mismo orden que el caso sin restricción.

Añadir que habría una posible restricción más. Las selecciones de tomas donde los grupos de estas fuesen los mismos, pero en días diferentes, van a dar el mismo gasto, siendo equivalentes en relación al gasto. Un ejemplo de esto son todos los casos de grabar una única toma diaria, aunque si tenemos en cuenta que día se graba cada toma entonces hay $n!$ posibilidades de ordenarlas, en todos esos casos el gasto va a ser el mismo, ya que los días son independientes entre si. El cálculo de esta restricción ya sí sería más complejo.   

Modelo para el espacio de soluciones<br>
(*) ¿Cual es la estructura de datos que mejor se adapta al problema? Argumentalo.(Es posible que hayas elegido una al principio y veas la necesidad de cambiar, argumentalo)


La estructura que seguramente mejor se adapta al problema, o al menos la más simple, es una lista de tamaño $n$(tomas), donde la posición o índice se corresponda al número de toma y el valor al día de grabación de esa toma, siendo el primer día posible el 0.

Respetar la restricción de 6 tomas diarias máximas implica que la lista solución deberá cumplir la restricción de que haya como máximo 6 elementos iguales.



In [134]:
sol = []
for i in range(30):
  while sol.count(i) < 6:
    if len(sol) < 30:
      sol.append(i)
    else:
      break
  if len(sol) == 30:
    break

sol

[0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 4,
 4,
 4,
 4,
 4,
 4]

Según el modelo para el espacio de soluciones<br>
(*)¿Cual es la función objetivo?

(*)¿Es un problema de maximización o minimización?

La función objetivo es una que calcule el gasto total por los servicios de los actores, teniendo en cuenta que una vez que un actor ha ido un día, el gasto de ese actor para ese día será el mismo independientemente del número de tomas grabadas. Como el gasto por actor y por día es el mismo para todos, por simplicidad se escogerá que ese gasto es 1. De esta manera si se quisiese conocer el gasto total real en el futuro, simplemente habría que multiplicar el gasto calculado por el sueldo por día de los actores.

Este problema sería un problema de minimización de la función objetivo, en este caso, el gasto total por los actores.

In [135]:
import numpy as np

tomas_actores = np.array( 
                [[1,	1,	1,	1,	1,	0,	0,	0,	0,	0],
                 [0,	0,	1,	1,	1,	0,	0,	0,	0,	0],
                 [0,	1,	0,	0,	1,	0,	1,	0,	0,	0],
                 [1,	1,	0,	0,	0,	0,	1,	1,	0,	0],
                 [0,	1,	0,	1,	0,	0,	0,	1,	0,	0],
                 [1,	1,	0,	1,	1,	0,	0,	0,	0,	0],
                 [1,	1,	0,	1,	1,	0,	0,	0,	0,	0],
                 [1,	1,	0,	0,	0,	1,	0,	0,	0,	0],
                 [1,	1,	0,	1,	0,	0,	0,	0,	0,	0],
                 [1,	1,	0,	0,	0,	1,	0,	0,	1,	0],
                 [1,	1,	1,	0,	1,	0,	0,	1,	0,	0],
                 [1,	1,	1,	1,	0,	1,	0,	0,	0,	0],
                 [1,	0,	0,	1,	1,	0,	0,	0,	0,	0],
                 [1,	0,	1,	0,	0,	1,	0,	0,	0,	0],
                 [1,	1,	0,	0,	0,	0,	1,	0,	0,	0],
                 [0,	0,	0,	1,	0,	0,	0,	0,	0,	1],
                 [1,	0,	1,	0,	0,	0,	0,	0,	0,	0],
                 [0,	0,	1,	0,	0,	1,	0,	0,	0,	0],
                 [1,	0,	1,	0,	0,	0,  0,	0,	0,	0],
                 [1,	0,	1,	1,	1,	0,	0,	0,	0,	0],
                 [0,	0,	0,	0,	0,	1,	0,	1,	0,	0],
                 [1,	1,	1,	1,	0,	0,	0,	0,	0,	0],
                 [1,	0,	1,	0,	0,	0,	0,	0,	0,	0],
                 [0,	0,	1,	0,	0,	1,	0,	0,	0,	0],
                 [1,	1,	0,	1,	0,	0,	0,	0,	0,	1],
                 [1,	0,	1,	0,	1,	0,	0,	0,	1,	0],
                 [0,	0,	0,  1,	1,	0,	0,	0,	0,	0],
                 [1,	0,	0,	1,	0,	0,	0,	0,	0,	0],
                 [1,	0,	0,	0,	1,	1,	0,	0,	0,	0],
                 [1,	0,	0,	1,	0,	0,	0,	0,	0,	0]])

In [136]:
def gasto(sol, tomas_actores):
  actores_dias = np.zeros([tomas_actores.shape[1], int(max(sol))+1])
  gasto = 0
  for n in range(len(sol)): # Para cada toma
    for j in range(tomas_actores.shape[1]): # Para cada actor
    # Si ese actor está en la toma n y aún no había ido ese día se suma al gasto
      if tomas_actores[n, j] == 1 and actores_dias[j, int(sol[n])] == 0:
        actores_dias[j, int(sol[n])] = 1
        gasto += 1
      elif tomas_actores[n, j] == 1: # Si está pero ya había ido no suma al gasto
        actores_dias[j, int(sol[n])] += 1 # Para ver cuantas tomas ha tenido ese día
  return gasto, actores_dias

gasto(sol, tomas_actores)

(38, array([[3., 6., 4., 4., 5.],
        [5., 6., 1., 1., 1.],
        [2., 2., 3., 5., 1.],
        [4., 3., 2., 2., 4.],
        [4., 2., 1., 1., 3.],
        [0., 3., 2., 2., 1.],
        [2., 0., 1., 0., 0.],
        [2., 1., 0., 1., 0.],
        [0., 1., 0., 0., 1.],
        [0., 0., 1., 0., 1.]]))

La función devuelve el gasto total y la matriz actores_dias, la cual cada fila es un actor y cada columna un día. Los valores en ella son el número de tomas que el actor (fila) ha hecho en el día (columna).

Además, tambíen es sencillo calcular la cota inferior y superior del problema total. Serían las siguientes:

In [145]:
def cota_inferior_total(tomas_actores, r=6):
  J = tomas_actores.shape[1]
  cota = 0
  for j in range(J): # Para cada actor
  # El mínimo de días que necesitaría para hacer todas sus tomas
    cota += np.ceil(np.sum(tomas_actores[:, j]) / r)

  return cota

def cota_superior_total(tomas_actores, r=6):
  J = tomas_actores.shape[1]
  cota = 0
  for j in range(J): # Para cada actor
  # El caso de que cada actor vaya un día para cada toma
    cota += np.sum(tomas_actores[:, j])

  return cota

print('Cota inferior:', cota_inferior_total(tomas_actores))
print('Cota superior:', cota_superior_total(tomas_actores))

Cota inferior: 21.0
Cota superior: 94


Diseña un algoritmo para resolver el problema por fuerza bruta

Respuesta

Calcula la complejidad del algoritmo por fuerza bruta

Respuesta

(*)Diseña un algoritmo que mejore la complejidad del algortimo por fuerza bruta. Argumenta porque crees que mejora el algoritmo por fuerza bruta

Para resolver el problema se va a hacer uso de un algoritmo voraz, el cual va a seguir las siguientes reglas. 

Para cada día se va a comenzar escogiendo la toma con más actores involucrados que quede disponible, en caso de empate se escogerá la última que apareciese. 

Una vez escogida la primera del día, la siguiente toma se escogera contando en el resto de tomas disponibles el número de coincidencias entre sus actores y la última escogida. En caso de empate se seleccionará la última que apareciese. 

Así sucesivamente hasta completar el número máximo de tomas diarias. Una vez alcanzado se pasará al siguiente día y se volverá a repetir el proceso, así hasta que todas las tomas hayan sido escogidas.

In [146]:
def voraz(tomas_actores, r=6):
  N = tomas_actores.shape[0] # Número de tomas
  J = tomas_actores.shape[1] # Número de actores
  sol = np.ones(N) * -1 # Inicialización de la solución
  tomas_usadas = np.zeros(N) # Para comprobar si una toma ha sido usada o no
  for i in range(int(np.ceil(N/r))): # Cálculo de las tomas para cada día
    if tomas_usadas.sum() == N: # Si todas las tomas ya han sido usadas terminar
      break
    n_actores = -1
    for n in range(N): # Comprobar para cada toma
      if tomas_usadas[n] == 0: # Solo si la toma aún no ha sido usada
        if np.sum(tomas_actores[n, :]) >= n_actores: # La que más actores tenga
          n_actores = np.sum(tomas_actores[n, :])
          toma_max = n # La toma con más actores por ahora es n
    
    sol[toma_max] = i # Se añade la toma con más actores a la solución
    tomas_usadas[toma_max] = 1 # Se indica como ya usada
    if tomas_usadas.sum() == N: # Si todas las tomas ya han sido usadas terminar
      break
    toma_ant = toma_max # Para saber cual era la toma anterior

    for _ in range(r-1): # Se completan el resto de tomas del día (r-1)
      act_coincide_max = -1
      for n in range(N): # Comprobar para cada toma
        if tomas_usadas[n] == 0: # Solo si la toma aún no ha sido usada
          act_coincide = 0
          for j in range(J): # Para cada actor
          # Si la toma anterior y la nueva valen ambas 1 para el actor j
            if tomas_actores[toma_ant, j] == 1 and tomas_actores[n, j] == 1:
              act_coincide += 1 # Si es así se añade una coincidencia más
          
          if act_coincide >= act_coincide_max: # Solo nos quedamos la que más tenga
            act_coincide_max = act_coincide
            toma_max = n
      
      sol[toma_max] = i # Se añade la toma con más coincidencias a la solución
      tomas_usadas[toma_max] = 1 # Se indica como ya usada
      if tomas_usadas.sum() == N: # Si todas las tomas ya han sido usadas terminar
        break
      toma_ant = toma_max # Se cambia la toma anterior a la nueva

  return sol

solucion = voraz(tomas_actores)

print(solucion)
print('Gasto total:', gasto(solucion, tomas_actores)[0])

[0. 3. 3. 3. 4. 1. 1. 2. 1. 2. 0. 0. 1. 2. 3. 4. 4. 2. 4. 0. 4. 0. 4. 2.
 1. 0. 3. 3. 2. 1.]
Gasto total: 33


En principio el resultado debería, si no ser el más óptimo (es difícil de saber), sí que acercarse bastante a la solución óptima. 

(*)Calcula la complejidad del algoritmo 

El número de operaciones, considerando que $n$ es el número de tomas, $j$ el número de actores y $r$ las restricción de tomas máximas al día, empezando de arriba hacia abajo es:

$$\mathrm{Operaciones}=4+\frac{n}{r}\left(2+4n+4+\left(r-1\right)\left(1+n\left(2+2j+3\right)+4\right)\right)$$

Una vez operado todo queda:

$$\mathrm{Operaciones}=\left(5+2j-\frac{2j+1}{r}\right)n^{2}+\left(5+\frac{1}{r}\right)n+4$$

Aunque es cierto que esto sería en el peor de los casos, ya que algunos bucles podrían no llegar a realizarse completamente. Pero la complejidad se debería ver poco afectada en este caso.

Por tanto la complejidad será $O\left(n^{2}\right)$.

Según el problema (y tenga sentido), diseña un juego de datos de entrada aleatorios

Respuesta

In [139]:
# Matriz de 30 tomas(filas) y 10 actores(columnas) de 0 y 1
problema_aleatorio = np.random.randint(2, size=(30,10))
print(problema_aleatorio)

[[1 1 0 1 1 1 0 1 1 0]
 [0 1 0 1 0 1 1 1 0 0]
 [0 0 1 0 0 0 1 1 0 0]
 [1 0 0 0 1 1 1 1 0 1]
 [0 0 0 1 1 0 1 0 1 0]
 [1 1 0 0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0 1 0 1]
 [0 0 0 1 1 1 1 1 1 0]
 [0 1 0 0 0 0 0 0 1 1]
 [0 0 0 1 1 1 1 1 0 1]
 [0 1 1 1 0 1 0 1 0 1]
 [0 0 1 0 0 0 1 1 0 1]
 [0 0 1 0 1 1 0 1 1 0]
 [1 1 0 1 0 0 0 1 0 1]
 [1 1 0 1 1 0 1 1 0 0]
 [0 0 1 0 1 1 1 1 1 0]
 [1 1 1 0 1 1 1 0 1 1]
 [1 1 0 1 1 1 1 1 1 0]
 [0 1 0 1 0 0 0 0 0 0]
 [0 0 1 0 1 0 1 1 0 0]
 [1 0 1 0 0 1 1 1 0 1]
 [1 1 1 1 1 1 0 0 1 1]
 [1 0 0 1 1 1 1 0 1 1]
 [0 1 0 1 0 0 1 1 1 0]
 [1 0 0 1 1 1 0 1 1 0]
 [0 1 1 0 1 1 0 1 1 0]
 [0 0 0 1 1 1 1 1 0 0]
 [0 0 1 1 1 0 0 1 1 0]
 [1 1 0 0 1 0 1 1 1 0]
 [0 1 1 1 1 1 1 0 1 0]]


Aplica el algoritmo al juego de datos generado

Respuesta

In [144]:
# Muestra por pantalla la cota inferior y superior del gasto del problema
print('Cota inferior:', cota_inferior_total(problema_aleatorio))
print('Cota superior:', cota_superior_total(problema_aleatorio))
print('\n')
# Calculo de la solución
solucion_aleatoria = voraz(problema_aleatorio)

# Muestra por pantalla la solución y gasto
print(solucion_aleatoria)
print('Gasto total:', gasto(solucion_aleatoria, problema_aleatorio)[0])

Cota inferior: 30.0
Cota superior: 161


[0. 2. 4. 3. 4. 4. 3. 1. 4. 1. 2. 3. 3. 4. 2. 1. 0. 0. 4. 3. 2. 0. 1. 2.
 0. 1. 1. 3. 2. 0.]
Gasto total: 48


Enumera las referencias que has utilizado(si ha sido necesario) para llevar a cabo el trabajo

Respuesta

Describe brevemente las lineas de como crees que es posible avanzar en el estudio del problema. Ten en cuenta incluso posibles variaciones del problema y/o variaciones al alza del tamaño

Probablemente el algoritmo más indicado si se quiere hallar la solución más óptima de todas, y no solo una cercana a ella, sea el de ramificación y poda. Aunque, en ese caso hallar las cotas superiores e inferiores de los nodos seguramente no sería una tarea sencilla debido al gran número de posibilidades, inicialmente seguramente sería simple ir quitandose las ramas que claramente son menos óptimas. Básicamente para este caso, todas las ramas que tengan pocas tomas cada día. 

Tal y como se indicó en la pregunta de las posibilidades con restricciones, el número de posiblidades también se podría reducir más si a la hora de inspecionar las posibles soluciones se evitasen las selecciones de tomas donde los grupos de estas fuesen los mismos, pero en días diferentes, ya que el gasto va a ser el mismo en esos casos.

Haciendose esto se podrían evitar un gran número de soluciones, que aunque diferentes, tendrían el mismo gasto.